### ISSUE TITLE
ImportError: cannot import name 'config_params' from 'config' (unknown location)

### ISSUE THREAD

**Issue by jmueducn** [yhydhx/AugGPT#2]
There is no config_params.py file ,how to solve it?

**Comment by yhydhx** [comment]
Hi, could you provide more detail?

**Comment by jmueducn** [comment]
when I run:
 python AugGPT.py --task pretrain --cuda 1 --dataset PubMed20k
Traceback (most recent call last):
  File "AugGPT.py", line 11, in <module>
    from methods import *
  File "/data2/cpy/AugGPT-main/methods.py", line 20, in <module>
    from config import config_params 
ImportError: cannot import name 'config_params' from 'config' (unknown location)

It seems there is no file name config_params.py in the folder

**Comment by jmueducn** [comment]
OK I now see the file updated, thanks
